image: maven:3-openjdk-18

build: 
  stage: build
  tags:
    - maven
    - java
  script: 
    - mvn compile


unit-test:
  tags:
    - maven
    - java
  stage: test
  script:
    - mvn test

cache:
  paths:
    - .m2/repository/
    - target/
  
