package com.wriesnig.api.git;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

public class GitApiResponses {
    private static final String RESPONSE_FULL_NAMES = """
            {
              "total_count": 2,
              "incomplete_results": false,
              "items": [
                {
                  "login": "jonhoo",
                  "id": 176295,
                  "node_id": "MDQ6VXNlcjE3NjI5NQ==",
                  "avatar_url": "https://avatars.githubusercontent.com/u/176295?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/jonhoo",
                  "html_url": "https://github.com/jonhoo",
                  "followers_url": "https://api.github.com/users/jonhoo/followers",
                  "following_url": "https://api.github.com/users/jonhoo/following{/other_user}",
                  "gists_url": "https://api.github.com/users/jonhoo/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/jonhoo/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/jonhoo/subscriptions",
                  "organizations_url": "https://api.github.com/users/jonhoo/orgs",
                  "repos_url": "https://api.github.com/users/jonhoo/repos",
                  "events_url": "https://api.github.com/users/jonhoo/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/jonhoo/received_events",
                  "type": "User",
                  "site_admin": false,
                  "score": 1.0
                },
                {
                  "login": "jskeet",
                  "id": 17011,
                  "node_id": "MDQ6VXNlcjE3MDEx",
                  "avatar_url": "https://avatars.githubusercontent.com/u/17011?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/jskeet",
                  "html_url": "https://github.com/jskeet",
                  "followers_url": "https://api.github.com/users/jskeet/followers",
                  "following_url": "https://api.github.com/users/jskeet/following{/other_user}",
                  "gists_url": "https://api.github.com/users/jskeet/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/jskeet/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/jskeet/subscriptions",
                  "organizations_url": "https://api.github.com/users/jskeet/orgs",
                  "repos_url": "https://api.github.com/users/jskeet/repos",
                  "events_url": "https://api.github.com/users/jskeet/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/jskeet/received_events",
                  "type": "User",
                  "site_admin": false,
                  "score": 1.0
                }
              ]
            }""";

    private static final String RESPONSE_LOGIN = """
            {
               "login": "octocat",
               "id": 1,
               "node_id": "MDQ6VXNlcjE=",
               "avatar_url": "https://github.com/images/error/octocat_happy.gif",
               "gravatar_id": "",
               "url": "https://api.github.com/users/octocat",
               "html_url": "https://github.com/octocat",
               "followers_url": "https://api.github.com/users/octocat/followers",
               "following_url": "https://api.github.com/users/octocat/following{/other_user}",
               "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
               "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
               "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
               "organizations_url": "https://api.github.com/users/octocat/orgs",
               "repos_url": "https://api.github.com/users/octocat/repos",
               "events_url": "https://api.github.com/users/octocat/events{/privacy}",
               "received_events_url": "https://api.github.com/users/octocat/received_events",
               "type": "User",
               "site_admin": false,
               "name": "monalisa octocat",
               "company": "GitHub",
               "blog": "https://github.com/blog",
               "location": "San Francisco",
               "email": "octocat@github.com",
               "hireable": false,
               "bio": "There once was...",
               "twitter_username": "monatheoctocat",
               "public_repos": 2,
               "public_gists": 1,
               "followers": 20,
               "following": 0,
               "created_at": "2008-01-14T04:33:35Z",
               "updated_at": "2008-01-14T04:33:35Z",
               "private_gists": 81,
               "total_private_repos": 100,
               "owned_private_repos": 100,
               "disk_usage": 10000,
               "collaborators": 8,
               "two_factor_authentication": true,
               "plan": {
                 "name": "Medium",
                 "space": 400,
                 "private_repos": 20,
                 "collaborators": 0
               }
             }""";

    private static final String RESPONSE_REPOS = """
            [
                {
                   "id": 469132559,
                   "node_id": "R_kgDOG_ZlDw",
                   "name": "Runner",
                   "full_name": "johannwriesnig/Runner",
                   "private": false,
                   "owner": {
                     "login": "johannwriesnig",
                     "id": 80066151,
                     "node_id": "MDQ6VXNlcjgwMDY2MTUx",
                     "avatar_url": "https://avatars.githubusercontent.com/u/80066151?v=4",
                     "gravatar_id": "",
                     "url": "https://api.github.com/users/johannwriesnig",
                     "html_url": "https://github.com/johannwriesnig",
                     "followers_url": "https://api.github.com/users/johannwriesnig/followers",
                     "following_url": "https://api.github.com/users/johannwriesnig/following{/other_user}",
                     "gists_url": "https://api.github.com/users/johannwriesnig/gists{/gist_id}",
                     "starred_url": "https://api.github.com/users/johannwriesnig/starred{/owner}{/repo}",
                     "subscriptions_url": "https://api.github.com/users/johannwriesnig/subscriptions",
                     "organizations_url": "https://api.github.com/users/johannwriesnig/orgs",
                     "repos_url": "https://api.github.com/users/johannwriesnig/repos",
                     "events_url": "https://api.github.com/users/johannwriesnig/events{/privacy}",
                     "received_events_url": "https://api.github.com/users/johannwriesnig/received_events",
                     "type": "User",
                     "site_admin": false
                   },
                   "html_url": "https://github.com/johannwriesnig/Runner",
                   "description": "GameBoy-Game written in assembly",
                   "fork": false,
                   "url": "https://api.github.com/repos/johannwriesnig/Runner",
                   "forks_url": "https://api.github.com/repos/johannwriesnig/Runner/forks",
                   "keys_url": "https://api.github.com/repos/johannwriesnig/Runner/keys{/key_id}",
                   "collaborators_url": "https://api.github.com/repos/johannwriesnig/Runner/collaborators{/collaborator}",
                   "teams_url": "https://api.github.com/repos/johannwriesnig/Runner/teams",
                   "hooks_url": "https://api.github.com/repos/johannwriesnig/Runner/hooks",
                   "issue_events_url": "https://api.github.com/repos/johannwriesnig/Runner/issues/events{/number}",
                   "events_url": "https://api.github.com/repos/johannwriesnig/Runner/events",
                   "assignees_url": "https://api.github.com/repos/johannwriesnig/Runner/assignees{/user}",
                   "branches_url": "https://api.github.com/repos/johannwriesnig/Runner/branches{/branch}",
                   "tags_url": "https://api.github.com/repos/johannwriesnig/Runner/tags",
                   "blobs_url": "https://api.github.com/repos/johannwriesnig/Runner/git/blobs{/sha}",
                   "git_tags_url": "https://api.github.com/repos/johannwriesnig/Runner/git/tags{/sha}",
                   "git_refs_url": "https://api.github.com/repos/johannwriesnig/Runner/git/refs{/sha}",
                   "trees_url": "https://api.github.com/repos/johannwriesnig/Runner/git/trees{/sha}",
                   "statuses_url": "https://api.github.com/repos/johannwriesnig/Runner/statuses/{sha}",
                   "languages_url": "https://api.github.com/repos/johannwriesnig/Runner/languages",
                   "stargazers_url": "https://api.github.com/repos/johannwriesnig/Runner/stargazers",
                   "contributors_url": "https://api.github.com/repos/johannwriesnig/Runner/contributors",
                   "subscribers_url": "https://api.github.com/repos/johannwriesnig/Runner/subscribers",
                   "subscription_url": "https://api.github.com/repos/johannwriesnig/Runner/subscription",
                   "commits_url": "https://api.github.com/repos/johannwriesnig/Runner/commits{/sha}",
                   "git_commits_url": "https://api.github.com/repos/johannwriesnig/Runner/git/commits{/sha}",
                   "comments_url": "https://api.github.com/repos/johannwriesnig/Runner/comments{/number}",
                   "issue_comment_url": "https://api.github.com/repos/johannwriesnig/Runner/issues/comments{/number}",
                   "contents_url": "https://api.github.com/repos/johannwriesnig/Runner/contents/{+path}",
                   "compare_url": "https://api.github.com/repos/johannwriesnig/Runner/compare/{base}...{head}",
                   "merges_url": "https://api.github.com/repos/johannwriesnig/Runner/merges",
                   "archive_url": "https://api.github.com/repos/johannwriesnig/Runner/{archive_format}{/ref}",
                   "downloads_url": "https://api.github.com/repos/johannwriesnig/Runner/downloads",
                   "issues_url": "https://api.github.com/repos/johannwriesnig/Runner/issues{/number}",
                   "pulls_url": "https://api.github.com/repos/johannwriesnig/Runner/pulls{/number}",
                   "milestones_url": "https://api.github.com/repos/johannwriesnig/Runner/milestones{/number}",
                   "notifications_url": "https://api.github.com/repos/johannwriesnig/Runner/notifications{?since,all,participating}",
                   "labels_url": "https://api.github.com/repos/johannwriesnig/Runner/labels{/name}",
                   "releases_url": "https://api.github.com/repos/johannwriesnig/Runner/releases{/id}",
                   "deployments_url": "https://api.github.com/repos/johannwriesnig/Runner/deployments",
                   "created_at": "2022-03-12T16:08:58Z",
                   "updated_at": "2022-06-25T22:25:00Z",
                   "pushed_at": "2022-07-21T13:25:00Z",
                   "git_url": "git://github.com/johannwriesnig/Runner.git",
                   "ssh_url": "git@github.com:johannwriesnig/Runner.git",
                   "clone_url": "https://github.com/johannwriesnig/Runner.git",
                   "svn_url": "https://github.com/johannwriesnig/Runner",
                   "homepage": "",
                   "size": 152,
                   "stargazers_count": 0,
                   "watchers_count": 0,
                   "language": "Assembly",
                   "has_issues": true,
                   "has_projects": true,
                   "has_downloads": true,
                   "has_wiki": true,
                   "has_pages": false,
                   "has_discussions": false,
                   "forks_count": 0,
                   "mirror_url": null,
                   "archived": false,
                   "disabled": false,
                   "open_issues_count": 0,
                   "license": null,
                   "allow_forking": true,
                   "is_template": false,
                   "web_commit_signoff_required": false,
                   "topics": [
              
                   ],
                   "visibility": "public",
                   "forks": 0,
                   "open_issues": 0,
                   "watchers": 0,
                   "default_branch": "main"
                 },
                 {
                   "id": 344583578,
                   "node_id": "MDEwOlJlcG9zaXRvcnkzNDQ1ODM1Nzg=",
                   "name": "SE2_Einzelbeispiel",
                   "full_name": "johannwriesnig/SE2_Einzelbeispiel",
                   "private": false,
                   "owner": {
                     "login": "johannwriesnig",
                     "id": 80066151,
                     "node_id": "MDQ6VXNlcjgwMDY2MTUx",
                     "avatar_url": "https://avatars.githubusercontent.com/u/80066151?v=4",
                     "gravatar_id": "",
                     "url": "https://api.github.com/users/johannwriesnig",
                     "html_url": "https://github.com/johannwriesnig",
                     "followers_url": "https://api.github.com/users/johannwriesnig/followers",
                     "following_url": "https://api.github.com/users/johannwriesnig/following{/other_user}",
                     "gists_url": "https://api.github.com/users/johannwriesnig/gists{/gist_id}",
                     "starred_url": "https://api.github.com/users/johannwriesnig/starred{/owner}{/repo}",
                     "subscriptions_url": "https://api.github.com/users/johannwriesnig/subscriptions",
                     "organizations_url": "https://api.github.com/users/johannwriesnig/orgs",
                     "repos_url": "https://api.github.com/users/johannwriesnig/repos",
                     "events_url": "https://api.github.com/users/johannwriesnig/events{/privacy}",
                     "received_events_url": "https://api.github.com/users/johannwriesnig/received_events",
                     "type": "User",
                     "site_admin": false
                   },
                   "html_url": "https://github.com/johannwriesnig/SE2_Einzelbeispiel",
                   "description": null,
                   "fork": false,
                   "url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel",
                   "forks_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/forks",
                   "keys_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/keys{/key_id}",
                   "collaborators_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/collaborators{/collaborator}",
                   "teams_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/teams",
                   "hooks_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/hooks",
                   "issue_events_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/issues/events{/number}",
                   "events_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/events",
                   "assignees_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/assignees{/user}",
                   "branches_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/branches{/branch}",
                   "tags_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/tags",
                   "blobs_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/git/blobs{/sha}",
                   "git_tags_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/git/tags{/sha}",
                   "git_refs_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/git/refs{/sha}",
                   "trees_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/git/trees{/sha}",
                   "statuses_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/statuses/{sha}",
                   "languages_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/languages",
                   "stargazers_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/stargazers",
                   "contributors_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/contributors",
                   "subscribers_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/subscribers",
                   "subscription_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/subscription",
                   "commits_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/commits{/sha}",
                   "git_commits_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/git/commits{/sha}",
                   "comments_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/comments{/number}",
                   "issue_comment_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/issues/comments{/number}",
                   "contents_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/contents/{+path}",
                   "compare_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/compare/{base}...{head}",
                   "merges_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/merges",
                   "archive_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/{archive_format}{/ref}",
                   "downloads_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/downloads",
                   "issues_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/issues{/number}",
                   "pulls_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/pulls{/number}",
                   "milestones_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/milestones{/number}",
                   "notifications_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/notifications{?since,all,participating}",
                   "labels_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/labels{/name}",
                   "releases_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/releases{/id}",
                   "deployments_url": "https://api.github.com/repos/johannwriesnig/SE2_Einzelbeispiel/deployments",
                   "created_at": "2021-03-04T19:16:42Z",
                   "updated_at": "2021-03-09T20:45:23Z",
                   "pushed_at": "2021-03-09T20:45:20Z",
                   "git_url": "git://github.com/johannwriesnig/SE2_Einzelbeispiel.git",
                   "ssh_url": "git@github.com:johannwriesnig/SE2_Einzelbeispiel.git",
                   "clone_url": "https://github.com/johannwriesnig/SE2_Einzelbeispiel.git",
                   "svn_url": "https://github.com/johannwriesnig/SE2_Einzelbeispiel",
                   "homepage": null,
                   "size": 81,
                   "stargazers_count": 0,
                   "watchers_count": 0,
                   "language": null,
                   "has_issues": true,
                   "has_projects": true,
                   "has_downloads": true,
                   "has_wiki": true,
                   "has_pages": false,
                   "has_discussions": false,
                   "forks_count": 0,
                   "mirror_url": null,
                   "archived": false,
                   "disabled": false,
                   "open_issues_count": 0,
                   "license": null,
                   "allow_forking": true,
                   "is_template": false,
                   "web_commit_signoff_required": false,
                   "topics": [
              
                   ],
                   "visibility": "public",
                   "forks": 0,
                   "open_issues": 0,
                   "watchers": 0,
                   "default_branch": "master"
                 },
                 {
                     "id": 601305315,
                     "node_id": "R_kgDOI9cw4w",
                     "name": "ControlNet",
                     "full_name": "johannwriesnig/ControlNet",
                     "private": false,
                     "owner": {
                       "login": "johannwriesnig",
                       "id": 80066151,
                       "node_id": "MDQ6VXNlcjgwMDY2MTUx",
                       "avatar_url": "https://avatars.githubusercontent.com/u/80066151?v=4",
                       "gravatar_id": "",
                       "url": "https://api.github.com/users/johannwriesnig",
                       "html_url": "https://github.com/johannwriesnig",
                       "followers_url": "https://api.github.com/users/johannwriesnig/followers",
                       "following_url": "https://api.github.com/users/johannwriesnig/following{/other_user}",
                       "gists_url": "https://api.github.com/users/johannwriesnig/gists{/gist_id}",
                       "starred_url": "https://api.github.com/users/johannwriesnig/starred{/owner}{/repo}",
                       "subscriptions_url": "https://api.github.com/users/johannwriesnig/subscriptions",
                       "organizations_url": "https://api.github.com/users/johannwriesnig/orgs",
                       "repos_url": "https://api.github.com/users/johannwriesnig/repos",
                       "events_url": "https://api.github.com/users/johannwriesnig/events{/privacy}",
                       "received_events_url": "https://api.github.com/users/johannwriesnig/received_events",
                       "type": "User",
                       "site_admin": false
                     },
                     "html_url": "https://github.com/johannwriesnig/ControlNet",
                     "description": "Let us control diffusion models",
                     "fork": true,
                     "url": "https://api.github.com/repos/johannwriesnig/ControlNet",
                     "forks_url": "https://api.github.com/repos/johannwriesnig/ControlNet/forks",
                     "keys_url": "https://api.github.com/repos/johannwriesnig/ControlNet/keys{/key_id}",
                     "collaborators_url": "https://api.github.com/repos/johannwriesnig/ControlNet/collaborators{/collaborator}",
                     "teams_url": "https://api.github.com/repos/johannwriesnig/ControlNet/teams",
                     "hooks_url": "https://api.github.com/repos/johannwriesnig/ControlNet/hooks",
                     "issue_events_url": "https://api.github.com/repos/johannwriesnig/ControlNet/issues/events{/number}",
                     "events_url": "https://api.github.com/repos/johannwriesnig/ControlNet/events",
                     "assignees_url": "https://api.github.com/repos/johannwriesnig/ControlNet/assignees{/user}",
                     "branches_url": "https://api.github.com/repos/johannwriesnig/ControlNet/branches{/branch}",
                     "tags_url": "https://api.github.com/repos/johannwriesnig/ControlNet/tags",
                     "blobs_url": "https://api.github.com/repos/johannwriesnig/ControlNet/git/blobs{/sha}",
                     "git_tags_url": "https://api.github.com/repos/johannwriesnig/ControlNet/git/tags{/sha}",
                     "git_refs_url": "https://api.github.com/repos/johannwriesnig/ControlNet/git/refs{/sha}",
                     "trees_url": "https://api.github.com/repos/johannwriesnig/ControlNet/git/trees{/sha}",
                     "statuses_url": "https://api.github.com/repos/johannwriesnig/ControlNet/statuses/{sha}",
                     "languages_url": "https://api.github.com/repos/johannwriesnig/ControlNet/languages",
                     "stargazers_url": "https://api.github.com/repos/johannwriesnig/ControlNet/stargazers",
                     "contributors_url": "https://api.github.com/repos/johannwriesnig/ControlNet/contributors",
                     "subscribers_url": "https://api.github.com/repos/johannwriesnig/ControlNet/subscribers",
                     "subscription_url": "https://api.github.com/repos/johannwriesnig/ControlNet/subscription",
                     "commits_url": "https://api.github.com/repos/johannwriesnig/ControlNet/commits{/sha}",
                     "git_commits_url": "https://api.github.com/repos/johannwriesnig/ControlNet/git/commits{/sha}",
                     "comments_url": "https://api.github.com/repos/johannwriesnig/ControlNet/comments{/number}",
                     "issue_comment_url": "https://api.github.com/repos/johannwriesnig/ControlNet/issues/comments{/number}",
                     "contents_url": "https://api.github.com/repos/johannwriesnig/ControlNet/contents/{+path}",
                     "compare_url": "https://api.github.com/repos/johannwriesnig/ControlNet/compare/{base}...{head}",
                     "merges_url": "https://api.github.com/repos/johannwriesnig/ControlNet/merges",
                     "archive_url": "https://api.github.com/repos/johannwriesnig/ControlNet/{archive_format}{/ref}",
                     "downloads_url": "https://api.github.com/repos/johannwriesnig/ControlNet/downloads",
                     "issues_url": "https://api.github.com/repos/johannwriesnig/ControlNet/issues{/number}",
                     "pulls_url": "https://api.github.com/repos/johannwriesnig/ControlNet/pulls{/number}",
                     "milestones_url": "https://api.github.com/repos/johannwriesnig/ControlNet/milestones{/number}",
                     "notifications_url": "https://api.github.com/repos/johannwriesnig/ControlNet/notifications{?since,all,participating}",
                     "labels_url": "https://api.github.com/repos/johannwriesnig/ControlNet/labels{/name}",
                     "releases_url": "https://api.github.com/repos/johannwriesnig/ControlNet/releases{/id}",
                     "deployments_url": "https://api.github.com/repos/johannwriesnig/ControlNet/deployments",
                     "created_at": "2023-02-13T19:42:21Z",
                     "updated_at": "2023-02-13T19:36:59Z",
                     "pushed_at": "2023-02-13T18:20:35Z",
                     "git_url": "git://github.com/johannwriesnig/ControlNet.git",
                     "ssh_url": "git@github.com:johannwriesnig/ControlNet.git",
                     "clone_url": "https://github.com/johannwriesnig/ControlNet.git",
                     "svn_url": "https://github.com/johannwriesnig/ControlNet",
                     "homepage": "",
                     "size": 65489,
                     "stargazers_count": 0,
                     "watchers_count": 0,
                     "language": null,
                     "has_issues": false,
                     "has_projects": true,
                     "has_downloads": true,
                     "has_wiki": true,
                     "has_pages": false,
                     "has_discussions": false,
                     "forks_count": 0,
                     "mirror_url": null,
                     "archived": false,
                     "disabled": false,
                     "open_issues_count": 0,
                     "license": {
                       "key": "apache-2.0",
                       "name": "Apache License 2.0",
                       "spdx_id": "Apache-2.0",
                       "url": "https://api.github.com/licenses/apache-2.0",
                       "node_id": "MDc6TGljZW5zZTI="
                     },
                     "allow_forking": true,
                     "is_template": false,
                     "web_commit_signoff_required": false,
                     "topics": [
              
                     ],
                     "visibility": "public",
                     "forks": 0,
                     "open_issues": 0,
                     "watchers": 0,
                     "default_branch": "main"
                   }
              ]""";

    public static InputStream getReposResponse(){
        return new ByteArrayInputStream(RESPONSE_REPOS.getBytes(StandardCharsets.UTF_8));
    }
    public static InputStream getLoginResponse(){
        return new ByteArrayInputStream(RESPONSE_LOGIN.getBytes(StandardCharsets.UTF_8));
    }
    public static InputStream getFullNamesResponse(){
        return new ByteArrayInputStream(RESPONSE_FULL_NAMES.getBytes(StandardCharsets.UTF_8));
    }
}
